import { jsPDF } from 'jspdf'

function formatDate(value) {
  if (!value) return '—'
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return String(value)
  return d.toLocaleDateString('en-PH', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function safeFilePart(text) {
  return String(text || 'Document')
    .replace(/[^\w\-]+/g, '_')
    .replace(/_+/g, '_')
    .slice(0, 60)
}

/**
 * Build and download an RHU Pila branded issued document PDF.
 * @returns {{ filename: string }}
 */
export function downloadIssuedDocumentPdf({
  title,
  patientName,
  patientDetails = {},
  purpose,
  notes,
  details = {},
  issuedAt,
  referenceNumber,
} = {}) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text('Republic of the Philippines', pageW / 2, y, { align: 'center' })
  y += 6
  doc.setFontSize(12)
  doc.text('Rural Health Unit of Pila', pageW / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text('Municipality of Pila, Laguna', pageW / 2, y, { align: 'center' })
  y += 8

  doc.setDrawColor(15, 118, 110)
  doc.setLineWidth(0.6)
  doc.line(20, y, pageW - 20, y)
  y += 12

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(String(title || 'Issued Document').toUpperCase(), pageW / 2, y, { align: 'center' })
  y += 12

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(`This is to certify that:`, 20, y)
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text(String(patientName || '—'), 20, y)
  y += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const lines = []
  if (patientDetails.age != null && patientDetails.age !== '') lines.push(`Age: ${patientDetails.age}`)
  if (patientDetails.sex) lines.push(`Sex: ${patientDetails.sex}`)
  if (patientDetails.birthdate) lines.push(`Birthdate: ${formatDate(patientDetails.birthdate)}`)
  if (patientDetails.barangay) {
    const addr = [patientDetails.house_no_purok, patientDetails.barangay, patientDetails.municipality || 'Pila', patientDetails.province || 'Laguna']
      .filter(Boolean)
      .join(', ')
    lines.push(`Address: ${addr}`)
  }
  for (const line of lines) {
    doc.text(line, 20, y)
    y += 6
  }

  y += 4
  if (purpose) {
    doc.setFont('helvetica', 'bold')
    doc.text('Purpose / Document', 20, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    const purposeLines = doc.splitTextToSize(String(purpose), pageW - 40)
    doc.text(purposeLines, 20, y)
    y += purposeLines.length * 5 + 4
  }

  if (notes) {
    doc.setFont('helvetica', 'bold')
    doc.text('Remarks', 20, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    const noteLines = doc.splitTextToSize(String(notes), pageW - 40)
    doc.text(noteLines, 20, y)
    y += noteLines.length * 5 + 4
  }

  const detailEntries = Object.entries(details || {}).filter(([k, v]) => {
    if (v == null || v === '') return false
    if (['outcome', 'notes', 'service_name'].includes(k)) return false
    if (typeof v === 'object') return false
    return true
  })
  if (detailEntries.length > 0) {
    doc.setFont('helvetica', 'bold')
    doc.text('Additional details', 20, y)
    y += 6
    doc.setFont('helvetica', 'normal')
    for (const [k, v] of detailEntries.slice(0, 12)) {
      const label = k.replace(/_/g, ' ')
      const text = doc.splitTextToSize(`${label}: ${v}`, pageW - 40)
      if (y > 260) break
      doc.text(text, 20, y)
      y += text.length * 5 + 1
    }
    y += 4
  }

  y = Math.max(y + 6, 230)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.text(`Date issued: ${formatDate(issuedAt)}`, 20, y)
  y += 6
  if (referenceNumber) {
    doc.text(`Reference: ${referenceNumber}`, 20, y)
    y += 6
  }

  y += 16
  doc.text('______________________________', pageW - 20, y, { align: 'right' })
  y += 5
  doc.setFontSize(9)
  doc.text('Authorized RHU Officer', pageW - 20, y, { align: 'right' })

  y = 285
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text(
    'Generated by HealthTrack RHU Pila. This electronic copy may be verified with the Rural Health Unit of Pila.',
    pageW / 2,
    y,
    { align: 'center', maxWidth: pageW - 30 },
  )

  const dateTag = issuedAt ? new Date(issuedAt).toISOString().slice(0, 10).replace(/-/g, '') : 'undated'
  const filename = `${safeFilePart(title)}-${dateTag}.pdf`
  doc.save(filename)
  return { filename }
}

export function pdfPayloadFromCertificate(row, patientName) {
  return {
    title: row.cert_type === 'medical'
      ? 'Medical Certificate'
      : row.cert_type === 'health_card'
        ? 'Health Card'
        : row.cert_type === 'death_cert_review'
          ? 'Death Certificate Review'
          : row.cert_type === 'pre_marriage'
            ? 'Pre-marriage Counseling Certificate'
            : 'Certificate',
    patientName: patientName || 'Patient',
    purpose: row.purpose,
    issuedAt: row.released_at || row.issued_at || row.created_at,
    referenceNumber: row.service_request_id ? String(row.service_request_id).slice(0, 8).toUpperCase() : null,
  }
}

export function pdfPayloadFromPermit(row, patientName) {
  const title =
    row.permit_type === 'sanitary'
      ? 'Sanitary Permit'
      : row.permit_type === 'cremation'
        ? 'Cremation Permit'
        : row.permit_type === 'transfer'
          ? 'Transfer Permit'
          : 'Exhumation Permit'
  const details = row.details && typeof row.details === 'object' ? row.details : {}
  return {
    title,
    patientName: row.applicant_name || patientName || 'Applicant',
    purpose: details.outcome || title,
    notes: details.notes || null,
    details,
    issuedAt: row.released_at || row.approved_at || row.created_at,
    referenceNumber: row.service_request_id ? String(row.service_request_id).slice(0, 8).toUpperCase() : null,
  }
}
