export const CHARTER_SERVICES = {
  animal_bite_anti_rabies: {
    title: 'Animal Bite',
    patientIntake: true,
    requirements: ['Vaccination card (if follow-up/booster) — secure from RHU'],
    steps: [
      { label: 'Registration', responsible: 'RHU Staff', minutes: 2 },
      { label: 'Vaccination proper', responsible: 'MHO / Nurse', minutes: 7 },
    ],
    feeNote: 'Php 0.00',
    intakeFields: [
      { name: 'bite_date', label: 'Date of bite', type: 'date', required: true },
      { name: 'animal_type', label: 'Type of animal', type: 'select', options: ['Dog', 'Cat', 'Other'], required: true },
      { name: 'bite_location', label: 'Body part bitten', type: 'text', required: true },
      {
        name: 'visit_type',
        label: 'Visit type',
        type: 'select',
        options: ['First dose', 'Follow-up / Booster'],
        required: true,
      },
      {
        name: 'has_vaccination_card',
        label: 'Do you have a vaccination card from RHU?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      { name: 'additional_notes', label: 'Additional details', type: 'textarea' },
    ],
  },
  outpatient_consultation: {
    title: 'Outpatient Consultation',
    patientIntake: false,
    staffIntakeNote:
      'For outpatient consultation, RHU staff will register you and the nurse will record your vital signs and chief complaint during your visit.',
    requirements: ['Previous medical record (if available) — secure from RHU'],
    steps: [
      { label: 'Registration', responsible: 'RHU Staff', minutes: 2 },
      { label: 'Vital signs', responsible: 'RHU Nurse', minutes: 5 },
      { label: 'Consultation', responsible: 'MHO', minutes: 15 },
    ],
    feeNote: 'Php 0.00',
  },
  exhumation_cremation_transfer_permit: {
    title: 'Exhumation / Cremation / Transfer Permit',
    patientIntake: true,
    requirements: [
      'Death certificate (certified true copy)',
      'Valid ID of requester',
      'Supporting documents as required by RHU',
    ],
    steps: [
      { label: 'Document submission', responsible: 'RHU Staff', minutes: 10 },
      { label: 'Evaluation & permit release', responsible: 'MHO / Staff', minutes: 15 },
    ],
    feeNote: 'Php 0.00',
    intakeFields: [
      {
        name: 'permit_type',
        label: 'Permit type',
        type: 'select',
        options: ['Exhumation', 'Cremation', 'Transfer'],
        required: true,
      },
      { name: 'deceased_name', label: 'Full name of deceased', type: 'text', required: true },
      { name: 'date_of_death', label: 'Date of death', type: 'date', required: true },
      { name: 'place_of_death', label: 'Place of death', type: 'text', required: true },
      { name: 'cause_of_death', label: 'Cause of death', type: 'text', required: true },
      { name: 'deceased_age', label: 'Age of deceased (for Transfer)', type: 'number' },
      { name: 'cemetery_or_destination', label: 'Cemetery / destination / crematory', type: 'text', required: true },
      { name: 'requester_name', label: 'Requester full name', type: 'text', required: true },
      { name: 'requester_relationship', label: 'Relationship to deceased', type: 'text', required: true },
      { name: 'requester_contact', label: 'Requester contact number', type: 'tel', required: true },
      { name: 'requester_address', label: 'Requester address', type: 'text', required: true },
      {
        name: 'documents_ready',
        label: 'Required documents ready for submission?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      { name: 'additional_notes', label: 'Additional details', type: 'textarea' },
    ],
  },
  review_death_certificate: {
    title: 'Review of Death Certificate',
    patientIntake: true,
    requirements: ['Death certificate for review', 'Valid ID of requester'],
    steps: [{ label: 'Application & evaluation', responsible: 'MHO / Nurse', minutes: 20 }],
    feeNote: 'Php 0.00',
    intakeFields: [
      { name: 'deceased_name', label: '1. Name on death certificate', type: 'text', required: true },
      { name: 'deceased_sex', label: '2. Sex', type: 'select', options: ['Male', 'Female'] },
      { name: 'date_of_death', label: '3. Date of death', type: 'date', required: true },
      { name: 'date_of_birth', label: '4. Date of birth', type: 'date' },
      { name: 'deceased_age', label: '5. Age at death', type: 'text' },
      { name: 'place_of_death', label: '6. Place of death', type: 'text', required: true },
      {
        name: 'deceased_civil_status',
        label: '7. Civil status',
        type: 'select',
        options: ['Single', 'Married', 'Widow', 'Widower', 'Annulled', 'Divorced'],
      },
      { name: 'cause_of_death', label: '19b. Causes of death', type: 'textarea', required: true },
      {
        name: 'corpse_disposal',
        label: '23. Corpse disposal',
        type: 'select',
        options: ['Burial', 'Cremation', 'Others'],
      },
      { name: 'requester_name', label: 'Requester full name', type: 'text', required: true },
      { name: 'requester_relationship', label: 'Relationship to deceased', type: 'text', required: true },
      { name: 'requester_contact', label: 'Requester contact number', type: 'tel', required: true },
      {
        name: 'review_reason',
        label: 'Reason for review',
        type: 'select',
        options: ['Correction of entries', 'Authentication / verification', 'Claim / insurance', 'Other'],
        required: true,
      },
      { name: 'purpose', label: 'Details / purpose of review', type: 'textarea', required: true },
      {
        name: 'has_death_certificate',
        label: 'Death certificate on hand?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
    ],
  },
  health_card_issuance: {
    title: 'Health Card Issuance',
    patientIntake: true,
    requirements: [
      'Food handlers: Laboratory request & result (from RHU)',
      'Non-food handlers: Medical certificate & laboratory request (from RHU)',
      'Valid ID',
    ],
    steps: [
      { label: 'Document evaluation', responsible: 'RHU Staff', minutes: 4 },
      { label: 'Examination', responsible: 'MHO / Nurse', minutes: 5 },
      { label: 'Payment & release', responsible: 'Nurse / RHU Staff', minutes: 1 },
    ],
    feeNote: 'Php 100.00',
    intakeFields: [
      {
        name: 'handler_type',
        label: 'Handler type (Food / Non-Food)',
        type: 'select',
        options: ['Food handler', 'Non-food handler'],
        required: true,
      },
      { name: 'applicant_name', label: 'NAME (as on Health Certificate)', type: 'text', required: true },
      { name: 'position_or_work', label: 'OCCUPATION', type: 'text', required: true },
      { name: 'applicant_age', label: 'AGE', type: 'number', required: true },
      {
        name: 'applicant_sex',
        label: 'SEX',
        type: 'select',
        options: ['Male', 'Female'],
        required: true,
      },
      { name: 'nationality', label: 'NATIONALITY', type: 'text', placeholder: 'Filipino' },
      { name: 'establishment_name', label: 'PLACE OF WORK — Establishment', type: 'text', required: true },
      { name: 'establishment_address', label: 'Establishment address', type: 'text', required: true },
      { name: 'applicant_contact', label: 'Contact number', type: 'tel', required: true },
      {
        name: 'has_lab_request',
        label: 'Laboratory request ready?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      {
        name: 'has_lab_result',
        label: 'Laboratory result ready?',
        type: 'select',
        options: ['Yes', 'No', 'Not applicable'],
        required: true,
      },
      {
        name: 'has_medical_certificate',
        label: 'Medical certificate ready? (non-food)',
        type: 'select',
        options: ['Yes', 'No', 'Not applicable'],
        required: true,
      },
      { name: 'additional_notes', label: 'Additional details', type: 'textarea' },
    ],
  },
  medical_certificate_issuance: {
    title: 'Medical Certificate Issuance',
    patientIntake: true,
    requirements: ['Consultation record — secure from RHU', 'Valid ID'],
    steps: [
      { label: 'Request & evaluation', responsible: 'RHU Staff', minutes: 3 },
      { label: 'Encoding & printing', responsible: 'MHO / Nurse', minutes: 3 },
      { label: 'Release', responsible: 'Nurse / RHU Staff', minutes: 1 },
    ],
    feeNote: 'Php 100.00 (Employment) · Php 150.00 (Medico-legal)',
    intakeFields: [
      {
        name: 'certificate_purposes',
        label: 'Purpose of medical certificate (select all that apply)',
        type: 'checkbox_group',
        options: ['PWD', 'Work / Employment', 'Financial assistance', "4P's", 'School', 'Medico-legal', 'Other'],
        required: true,
      },
      { name: 'certificate_purpose_other', label: 'If Other, please specify', type: 'text' },
      { name: 'employer_or_agency', label: 'Employer / school / requesting agency', type: 'text' },
      {
        name: 'had_recent_consultation',
        label: 'Had recent consultation at RHU?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      { name: 'consultation_date', label: 'Date of consultation (if any)', type: 'date' },
      { name: 'chief_complaint', label: 'Chief complaint / reason for certificate', type: 'textarea', required: true },
      { name: 'requester_contact', label: 'Contact number', type: 'tel', required: true },
      {
        name: 'urgency',
        label: 'Needed by',
        type: 'select',
        options: ['Same day', 'Within 3 days', 'No rush'],
        required: true,
      },
      { name: 'additional_notes', label: 'Additional notes for the doctor / nurse', type: 'textarea' },
    ],
  },
  sanitary_permit_issuance: {
    title: 'Sanitary Permit Issuance',
    patientIntake: true,
    requirements: [
      'Health certificate of workers',
      'Business permit application / DTI / Mayor’s permit docs',
      'Establishment floor plan / layout (if required)',
    ],
    steps: [
      { label: 'Document evaluation', responsible: 'RHU Staff', minutes: 10 },
      { label: 'Processing & release', responsible: 'MHO / Nurse', minutes: 15 },
    ],
    feeNote: 'Graduated fee by establishment area',
    intakeFields: [
      { name: 'establishment_name', label: 'Name of Establishment', type: 'text', required: true },
      {
        name: 'establishment_type',
        label: 'Nature of Business / Type',
        type: 'select',
        options: [
          'Food establishment',
          'Non-food establishment',
          'School',
          'Boarding house / lodging',
          'Industrial / manufacturing',
          'Other',
        ],
        required: true,
      },
      { name: 'nature_of_business', label: 'Nature of business (detail)', type: 'text' },
      { name: 'establishment_address', label: 'Address (include barangay)', type: 'text', required: true },
      { name: 'owner_name', label: 'Owner / operator full name', type: 'text', required: true },
      { name: 'owner_contact', label: 'Owner contact number', type: 'tel', required: true },
      { name: 'number_of_employees', label: 'Number of employees / workers', type: 'number', required: true },
      {
        name: 'has_health_certificate',
        label: 'Health certificate(s) of workers ready?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      {
        name: 'has_business_permit_application',
        label: 'Business permit application ready?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      {
        name: 'application_type',
        label: 'Application type',
        type: 'select',
        options: ['New', 'Renewal'],
        required: true,
      },
      { name: 'additional_notes', label: 'Additional details', type: 'textarea' },
    ],
  },
  tuberculosis_treatment_services: {
    title: 'Tuberculosis Treatment Services',
    patientIntake: true,
    requirements: ['Clinical record', 'X-ray result', 'Sputum (plema) result — from RHU'],
    steps: [
      { label: 'Document evaluation', responsible: 'RHU Staff', minutes: 5 },
      { label: 'Consultation', responsible: 'MHO', minutes: 10 },
      { label: 'Medicine / treatment pack release', responsible: 'RHU Staff', minutes: 1 },
    ],
    feeNote: 'Php 0.00',
    intakeFields: [
      { name: 'has_clinical_record', label: 'Clinical record available?', type: 'select', options: ['Yes', 'No'], required: true },
      { name: 'has_xray_result', label: 'X-ray result available?', type: 'select', options: ['Yes', 'No'], required: true },
      { name: 'has_sputum_result', label: 'Sputum result available?', type: 'select', options: ['Yes', 'No'], required: true },
      { name: 'symptoms', label: 'Current symptoms', type: 'textarea', required: true },
    ],
  },
  pre_marriage_counseling: {
    title: 'Pre-marriage Counseling',
    patientIntake: true,
    requirements: ['Copy of marriage license application', 'Valid IDs of both parties'],
    steps: [
      { label: 'Counseling session', responsible: 'RHU Staff', minutes: 230 },
      { label: 'Certificate of compliance', responsible: 'MHO', minutes: 10 },
    ],
    feeNote: 'Php 150.00',
    intakeFields: [
      { name: 'applicant_name', label: 'Your full name', type: 'text', required: true },
      { name: 'partner_name', label: "Partner's full name", type: 'text', required: true },
      {
        name: 'applicant_sex',
        label: 'Your sex',
        type: 'select',
        options: ['Male', 'Female'],
        required: true,
      },
      { name: 'applicant_age', label: 'Your age', type: 'number', required: true },
      { name: 'partner_age', label: "Partner's age", type: 'number', required: true },
      { name: 'wedding_date', label: 'Planned wedding date', type: 'date' },
      { name: 'wedding_place', label: 'Planned wedding venue / municipality', type: 'text' },
      {
        name: 'has_marriage_license_application',
        label: 'Marriage license application copy ready?',
        type: 'select',
        options: ['Yes', 'No'],
        required: true,
      },
      { name: 'contact_number', label: 'Best contact number', type: 'tel', required: true },
      { name: 'partner_contact', label: "Partner's contact number", type: 'tel' },
      { name: 'address', label: 'Current address (barangay, municipality)', type: 'text', required: true },
      { name: 'additional_notes', label: 'Questions / notes for the counselor', type: 'textarea' },
    ],
  },
}

export function getCharterByCode(code) {
  const key = (code ?? '').toString().trim()
  return CHARTER_SERVICES[key] ?? null
}

export function enrollmentNeedsPatientIntake(enrollment) {
  if (!enrollment) return false
  if (!enrollment.intake_required) return false
  return enrollment.status === 'intake_pending'
}
